# Generated by Django 3.0.3 on 2020-04-08 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='published',
        ),
    ]
