# Generated by Django 3.0.3 on 2020-04-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_remove_blog_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=models.CharField(choices=[('Python', 'Python'), ('javascript', 'javascript  '), ('vue js', 'vue js'), ('Express js', 'Express js'), ('Laravel', 'Laravel'), ('Flutter', 'Flutter'), ('Django', 'Django'), ('Es6', 'Es6'), ('IDEs', 'IDEs'), ('node js', 'node js')], default='Python', max_length=200),
        ),
    ]
