# Generated by Django 3.0.3 on 2020-04-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_blog_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='label',
            field=models.CharField(choices=[('noLabel', 'noLabel'), ('#100DaysOfCode', '#100DaysOfCode'), ('CodeChallenges', 'CodeChallenges')], default='noLabel', max_length=200),
        ),
    ]
