# Generated by Django 3.0.3 on 2020-04-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_blog_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='label',
            field=models.CharField(choices=[('noLabel', 'noLabel'), ('100DaysOfCode', '100DaysOfCode'), ('CodeChallenges', 'CodeChallenges')], default='noLabel', max_length=200),
        ),
    ]
