# Generated by Django 3.0.3 on 2020-04-09 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_auto_20200409_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='read_time',
        ),
    ]
